import { describe, it, expect, beforeEach } from "@jest/globals";
import { MarketplaceSearchService, MarketplaceSearchError } from "../marketplaceSearchService.js";
import { MarketplaceSearchQuery } from "../../validation/marketplaceSearchSchema.js";
import { Slot } from "../../types.js";

interface DbSlotRow {
  id: number;
  professional_id: string;
  start_time: Date;
  end_time: Date;
  category: string;
  price_cents: number;
  supplier_rating: number;
  status: string;
  created_at: Date;
}

/**
 * In-memory Mock Postgres Pool for MarketplaceSearchService tests.
 * Evaluates parameterized SQL queries generated by MarketplaceSearchService.
 */
class MockPgPool {
  public slots: DbSlotRow[] = [];

  async query(sql: string, params: any[] = []): Promise<{ rows: any[] }> {
    // Handle SELECT COUNT(*)
    if (sql.includes("COUNT(*)")) {
      const filtered = this.filterSlots(sql, params);
      return { rows: [{ total: filtered.length.toString() }] };
    }

    // Handle SELECT slots query
    let result = this.filterSlots(sql, params);

    // Apply ORDER BY
    if (sql.includes("ORDER BY supplier_rating DESC, id ASC")) {
      result.sort((a, b) => {
        if (b.supplier_rating !== a.supplier_rating) {
          return b.supplier_rating - a.supplier_rating;
        }
        return a.id - b.id;
      });
    } else if (sql.includes("ORDER BY price_cents ASC, id ASC")) {
      result.sort((a, b) => {
        if (a.price_cents !== b.price_cents) {
          return a.price_cents - b.price_cents;
        }
        return a.id - b.id;
      });
    } else if (sql.includes("ORDER BY supplier_rating DESC, price_cents ASC, id ASC")) {
      result.sort((a, b) => {
        if (b.supplier_rating !== a.supplier_rating) {
          return b.supplier_rating - a.supplier_rating;
        }
        if (a.price_cents !== b.price_cents) {
          return a.price_cents - b.price_cents;
        }
        return a.id - b.id;
      });
    }

    // Extract LIMIT and OFFSET from params based on query structure
    const limitMatch = sql.match(/LIMIT \$(\d+)/);
    const offsetMatch = sql.match(/OFFSET \$(\d+)/);

    let limit: number | undefined;
    let offset = 0;

    if (limitMatch) {
      const limitIndex = parseInt(limitMatch[1], 10) - 1;
      limit = params[limitIndex];
    }
    if (offsetMatch) {
      const offsetIndex = parseInt(offsetMatch[1], 10) - 1;
      offset = params[offsetIndex];
    }

    if (offset > 0) {
      result = result.slice(offset);
    }
    if (limit !== undefined) {
      result = result.slice(0, limit);
    }

    return {
      rows: result.map((s) => ({
        id: s.id,
        professional: s.professional_id,
        startTime: s.start_time,
        endTime: s.end_time,
        category: s.category,
        price_cents: s.price_cents,
        supplier_rating: s.supplier_rating,
        status: s.status,
        created_at: s.created_at,
      })),
    };
  }

  private filterSlots(sql: string, params: any[]): DbSlotRow[] {
    return this.slots.filter((slot) => {
      // Basic filters
      if (sql.includes("status =")) {
        const match = sql.match(/status = \$(\d+)/);
        if (match) {
          const statusParam = params[parseInt(match[1], 10) - 1];
          if (slot.status !== statusParam) return false;
        }
      }

      // Categories IN (...)
      const catMatch = sql.match(/category IN \(([^)]+)\)/);
      if (catMatch) {
        const paramIndexes = catMatch[1].match(/\$(\d+)/g)?.map((p) => parseInt(p.replace("$", ""), 10) - 1);
        if (paramIndexes) {
          const categories = paramIndexes.map((idx) => params[idx]);
          if (!categories.includes(slot.category)) return false;
        }
      }

      // Price range
      const minPriceMatch = sql.match(/price_cents >= \$(\d+)/);
      if (minPriceMatch) {
        const val = params[parseInt(minPriceMatch[1], 10) - 1];
        if (slot.price_cents < val) return false;
      }
      const maxPriceMatch = sql.match(/price_cents <= \$(\d+)/);
      if (maxPriceMatch) {
        const val = params[parseInt(maxPriceMatch[1], 10) - 1];
        if (slot.price_cents > val) return false;
      }

      // Rating range
      const minRatingMatch = sql.match(/supplier_rating >= \$(\d+)/);
      if (minRatingMatch) {
        const val = params[parseInt(minRatingMatch[1], 10) - 1];
        if (slot.supplier_rating < val) return false;
      }
      const maxRatingMatch = sql.match(/supplier_rating <= \$(\d+)/);
      if (maxRatingMatch) {
        const val = params[parseInt(maxRatingMatch[1], 10) - 1];
        if (slot.supplier_rating > val) return false;
      }

      // Time window
      const startTimeMatch = sql.match(/start_time >= \$(\d+)/);
      if (startTimeMatch) {
        const val = new Date(params[parseInt(startTimeMatch[1], 10) - 1]).getTime();
        if (slot.start_time.getTime() < val) return false;
      }
      const endTimeMatch = sql.match(/end_time <= \$(\d+)/);
      if (endTimeMatch) {
        const val = new Date(params[parseInt(endTimeMatch[1], 10) - 1]).getTime();
        if (slot.end_time.getTime() > val) return false;
      }

      // Cursor predicates
      if (sql.includes("supplier_rating < $") || sql.includes("price_cents > $")) {
        // rating sort mode
        if (sql.includes("supplier_rating < $") && !sql.includes("price_cents > $")) {
          const match = sql.match(/\(supplier_rating < \$(\d+) OR \(supplier_rating = \$\d+ AND id > \$(\d+)\)\)/);
          if (match) {
            const cRating = params[parseInt(match[1], 10) - 1];
            const cId = params[parseInt(match[2], 10) - 1];
            const satisfies =
              slot.supplier_rating < cRating ||
              (slot.supplier_rating === cRating && slot.id > cId);
            if (!satisfies) return false;
          }
        }

        // price sort mode
        if (sql.includes("price_cents > $") && !sql.includes("supplier_rating < $")) {
          const match = sql.match(/\(price_cents > \$(\d+) OR \(price_cents = \$\d+ AND id > \$(\d+)\)\)/);
          if (match) {
            const cPrice = params[parseInt(match[1], 10) - 1];
            const cId = params[parseInt(match[2], 10) - 1];
            const satisfies =
              slot.price_cents > cPrice ||
              (slot.price_cents === cPrice && slot.id > cId);
            if (!satisfies) return false;
          }
        }

        // relevance sort mode
        if (sql.includes("supplier_rating < $") && sql.includes("price_cents > $")) {
          const match = sql.match(
            /\(supplier_rating < \$(\d+) OR \(supplier_rating = \$\d+ AND price_cents > \$(\d+)\) OR \(supplier_rating = \$\d+ AND price_cents = \$\d+ AND id > \$(\d+)\)\)/
          );
          if (match) {
            const cRating = params[parseInt(match[1], 10) - 1];
            const cPrice = params[parseInt(match[2], 10) - 1];
            const cId = params[parseInt(match[3], 10) - 1];

            const satisfies =
              slot.supplier_rating < cRating ||
              (slot.supplier_rating === cRating && slot.price_cents > cPrice) ||
              (slot.supplier_rating === cRating && slot.price_cents === cPrice && slot.id > cId);
            if (!satisfies) return false;
          }
        }
      }

      return true;
    });
  }
}

describe("Marketplace Search Cursor Stability", () => {
  let pool: MockPgPool;
  let service: MarketplaceSearchService;

  beforeEach(() => {
    pool = new MockPgPool();
    service = new MarketplaceSearchService(pool as any);
  });

  const createSampleSlots = (count: number): DbSlotRow[] => {
    const slots: DbSlotRow[] = [];
    const baseTime = new Date("2026-02-01T10:00:00Z").getTime();

    for (let i = 1; i <= count; i++) {
      slots.push({
        id: i,
        professional_id: `prof-${i % 5}`,
        start_time: new Date(baseTime + i * 3600000),
        end_time: new Date(baseTime + (i + 1) * 3600000),
        category: i % 2 === 0 ? "haircut" : "plumbing",
        price_cents: 1000 + (i * 100) % 5000,
        supplier_rating: 3.0 + (i % 20) * 0.1,
        status: "available",
        created_at: new Date(),
      });
    }
    return slots;
  };

  describe("Cursor Encoding & Decoding Validation", () => {
    it("should encode sort key plus id tiebreak into valid cursor token", () => {
      const slot: Slot = {
        id: 42,
        professional: "prof-1",
        startTime: 1000,
        endTime: 2000,
        supplier_rating: 4.8,
        price_cents: 2500,
      };

      const tokenRating = service.encodeCursor(slot, "rating");
      const tokenPrice = service.encodeCursor(slot, "price");
      const tokenRelevance = service.encodeCursor(slot, "relevance");

      expect(typeof tokenRating).toBe("string");
      expect(typeof tokenPrice).toBe("string");
      expect(typeof tokenRelevance).toBe("string");

      const decodedRating = service.decodeCursor(tokenRating, "rating");
      expect(decodedRating.id).toBe(42);
      expect(decodedRating.rating).toBe(4.8);

      const decodedPrice = service.decodeCursor(tokenPrice, "price");
      expect(decodedPrice.id).toBe(42);
      expect(decodedPrice.price).toBe(2500);

      const decodedRelevance = service.decodeCursor(tokenRelevance, "relevance");
      expect(decodedRelevance.id).toBe(42);
      expect(decodedRelevance.rating).toBe(4.8);
      expect(decodedRelevance.price).toBe(2500);
    });

    it("should throw MarketplaceSearchError for malformed base64 cursor", () => {
      expect(() => service.decodeCursor("!!!invalid-base64!!!", "relevance")).toThrow(
        MarketplaceSearchError
      );
    });

    it("should throw MarketplaceSearchError for cursor sort mode mismatch", () => {
      const slot: Slot = { id: 1, professional: "p", startTime: 1, endTime: 2, price_cents: 100 };
      const tokenPrice = service.encodeCursor(slot, "price");

      expect(() => service.decodeCursor(tokenPrice, "rating")).toThrow(MarketplaceSearchError);
      expect(() => service.decodeCursor(tokenPrice, "rating")).toThrow("sortBy mismatch");
    });

    it("should throw MarketplaceSearchError if cursor is missing required sort key fields", () => {
      const badPayload = Buffer.from(JSON.stringify({ sortBy: "rating", id: 10 })).toString("base64");
      expect(() => service.decodeCursor(badPayload, "rating")).toThrow(MarketplaceSearchError);
      expect(() => service.decodeCursor(badPayload, "rating")).toThrow("rating must be a valid number");
    });

    it("should throw MarketplaceSearchError if cursor id is invalid", () => {
      const badPayload = Buffer.from(
        JSON.stringify({ sortBy: "price", price: 500, id: -1 })
      ).toString("base64");
      expect(() => service.decodeCursor(badPayload, "price")).toThrow(MarketplaceSearchError);
    });
  });

  describe("Deterministic Cursor Pagination Traversal", () => {
    it("should traverse entire slot dataset using nextCursor deterministically", async () => {
      pool.slots = createSampleSlots(35);

      const query: MarketplaceSearchQuery = {
        page: 1,
        limit: 10,
        sortBy: "relevance",
      };

      const accumulatedSlots: Slot[] = [];
      let currentCursor: string | undefined | null = undefined;

      do {
        const result = await service.search({ ...query, cursor: currentCursor ?? undefined });
        accumulatedSlots.push(...result.slots);
        currentCursor = result.nextCursor;
      } while (currentCursor);

      expect(accumulatedSlots.length).toBe(35);

      // Verify no duplicates
      const ids = accumulatedSlots.map((s) => s.id);
      const uniqueIds = new Set(ids);
      expect(uniqueIds.size).toBe(35);
    });
  });

  describe("Concurrent Slot Writes & Cursor Stability Invariants", () => {
    it("asserts zero gaps and zero duplicates under concurrent slot INSERTS", async () => {
      const initialSlots = createSampleSlots(40);
      pool.slots = [...initialSlots];

      const initialSlotIds = new Set(initialSlots.map((s) => s.id));
      const readSlotIds: number[] = [];
      let currentCursor: string | undefined = undefined;
      let pageCount = 0;
      let nextInsertId = 100;

      while (pageCount === 0 || currentCursor) {
        pageCount++;
        const result = await service.search({
          page: 1,
          limit: 5,
          sortBy: "relevance",
          cursor: currentCursor,
        });

        for (const slot of result.slots) {
          readSlotIds.push(slot.id);
        }

        // Simulate concurrent slot insertion between page requests
        if (pageCount < 6) {
          const newSlot: DbSlotRow = {
            id: nextInsertId++,
            professional_id: "prof-new",
            start_time: new Date(),
            end_time: new Date(Date.now() + 3600000),
            category: "haircut",
            price_cents: 2000,
            supplier_rating: 4.5,
            status: "available",
            created_at: new Date(),
          };
          pool.slots.push(newSlot);
        }

        currentCursor = result.nextCursor ?? undefined;
      }

      // Check invariant 1: Zero duplicates
      const readSet = new Set<number>();
      for (const id of readSlotIds) {
        expect(readSet.has(id)).toBe(false);
        readSet.add(id);
      }

      // Check invariant 2: All initial slots were returned without gap
      for (const initialId of initialSlotIds) {
        expect(readSet.has(initialId)).toBe(true);
      }
    });

    it("asserts zero gaps and zero duplicates under concurrent slot DELETES (delete-in-flight)", async () => {
      const initialSlots = createSampleSlots(50);
      pool.slots = [...initialSlots];

      const readSlotIds: number[] = [];
      const deletedSlotIds = new Set<number>();

      let currentCursor: string | undefined = undefined;
      let step = 0;

      while (step === 0 || currentCursor) {
        step++;
        const result = await service.search({
          page: 1,
          limit: 8,
          sortBy: "price",
          cursor: currentCursor,
        });

        for (const slot of result.slots) {
          readSlotIds.push(slot.id);
        }

        // Delete slots concurrently ahead and behind current page cursor
        if (step === 2 && pool.slots.length > 5) {
          // Delete slot ID 30 (ahead of cursor)
          const targetId = 30;
          pool.slots = pool.slots.filter((s) => s.id !== targetId);
          deletedSlotIds.add(targetId);
        }

        if (step === 3 && pool.slots.length > 5) {
          // Delete slot ID 5 (behind cursor)
          const targetId = 5;
          pool.slots = pool.slots.filter((s) => s.id !== targetId);
          deletedSlotIds.add(targetId);
        }

        currentCursor = result.nextCursor ?? undefined;
      }

      // Invariant 1: No duplicates
      const readSet = new Set<number>();
      for (const id of readSlotIds) {
        expect(readSet.has(id)).toBe(false);
        readSet.add(id);
      }

      // Invariant 2: No deleted slots returned
      for (const deletedId of deletedSlotIds) {
        expect(readSet.has(deletedId)).toBe(false);
      }

      // Invariant 3: All remaining initial slots were read without gap
      const expectedSurvivingIds = initialSlots
        .map((s) => s.id)
        .filter((id) => !deletedSlotIds.has(id));

      for (const id of expectedSurvivingIds) {
        expect(readSet.has(id)).toBe(true);
      }
    });

    it("handles price changes mid-page gracefully without infinite loops or duplicate reads", async () => {
      const initialSlots = createSampleSlots(30);
      pool.slots = [...initialSlots];

      const readSlots: Slot[] = [];
      let currentCursor: string | undefined = undefined;
      let step = 0;

      while (step === 0 || currentCursor) {
        step++;
        const result = await service.search({
          page: 1,
          limit: 6,
          sortBy: "price",
          cursor: currentCursor,
        });

        readSlots.push(...result.slots);

        // Mutate price of upcoming slot
        if (step === 1) {
          const slotToMutate = pool.slots.find((s) => s.id === 25);
          if (slotToMutate) {
            slotToMutate.price_cents = 50; // shift to lower price
          }
        }

        currentCursor = result.nextCursor ?? undefined;
      }

      // Verify no duplicates
      const ids = readSlots.map((s) => s.id);
      const uniqueIds = new Set(ids);
      expect(uniqueIds.size).toBe(ids.length);
    });
  });

  describe("Property-based Write Burst Size Invariants", () => {
    const burstSizes = [1, 5, 15, 30, 50];

    burstSizes.forEach((burstSize) => {
      it(`maintains cursor stability under concurrent write burst size = ${burstSize}`, async () => {
        const initialSlots = createSampleSlots(60);
        pool.slots = [...initialSlots];

        const initialSlotIds = new Set(initialSlots.map((s) => s.id));
        const readSlotIds: number[] = [];
        let currentCursor: string | undefined = undefined;
        let step = 0;
        let nextId = 200;

        while (step === 0 || currentCursor) {
          step++;
          const result = await service.search({
            page: 1,
            limit: 10,
            sortBy: "rating",
            cursor: currentCursor,
          });

          readSlotIds.push(...result.slots.map((s) => s.id));

          // Trigger burst write on step 2
          if (step === 2) {
            for (let b = 0; b < burstSize; b++) {
              pool.slots.push({
                id: nextId++,
                professional_id: `burst-prof-${b}`,
                start_time: new Date(),
                end_time: new Date(Date.now() + 3600000),
                category: "plumbing",
                price_cents: 1500 + b * 50,
                supplier_rating: 4.0,
                status: "available",
                created_at: new Date(),
              });
            }
          }

          currentCursor = result.nextCursor ?? undefined;
        }

        // Invariant: No duplicates
        const readSet = new Set<number>();
        for (const id of readSlotIds) {
          expect(readSet.has(id)).toBe(false);
          readSet.add(id);
        }

        // Invariant: All initial non-deleted slots are read
        for (const id of initialSlotIds) {
          expect(readSet.has(id)).toBe(true);
        }
      });
    });
  });

  describe("All-New-Writes Burst Edge Case", () => {
    it("handles sudden write burst of all-new slots mid-page traversal", async () => {
      pool.slots = createSampleSlots(20);

      const readSlots: Slot[] = [];
      let currentCursor: string | undefined = undefined;
      let pageIndex = 0;

      while (pageIndex === 0 || currentCursor) {
        pageIndex++;
        const result = await service.search({
          page: 1,
          limit: 5,
          sortBy: "relevance",
          cursor: currentCursor,
        });

        readSlots.push(...result.slots);

        if (pageIndex === 2) {
          // Burst insert 30 new items
          for (let i = 500; i < 530; i++) {
            pool.slots.push({
              id: i,
              professional_id: "burst-new",
              start_time: new Date(),
              end_time: new Date(Date.now() + 3600000),
              category: "haircut",
              price_cents: 3000,
              supplier_rating: 4.9,
              status: "available",
              created_at: new Date(),
            });
          }
        }

        currentCursor = result.nextCursor ?? undefined;
      }

      // Check no duplicates in entire stream
      const readIds = readSlots.map((s) => s.id);
      const uniqueIds = new Set(readIds);
      expect(uniqueIds.size).toBe(readIds.length);
    });
  });
});
